name = "caprica-media-group"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "caprica-media-db"
database_id = "588d9df7-1f9f-4556-8eb4-32e76a1134d5"

[vars]
SITE_NAME = "Caprica Media Group"
